### PR TITLE
Cleanup after 7.1.0 release

### PR DESCRIPTION
**Pull request by nmdefries**
Keep version on `dev` up to date with `main`.

### CODE REVIEW

**Comment by nmdefries** [comment]
`Release Main` failure is known, seems to be related to the [recent deprecation of Node12](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/), need to fix that on `dev` and do another merge into `main`.

**Comment by dsweber2** [comment]
do we have a way to tell the robots to run the CI again, after the other pull request was merged?

**Comment by nmdefries** [comment]
So https://github.com/cmu-delphi/forecast-eval/pull/293 was added to `dev`. We need to merge `dev` into `main` before trying to release `main` again using the automatic method (since otherwise it won't have the updated workflow file and will fail in the same way).

I can run the [`Release Main` workflow](https://github.com/cmu-delphi/forecast-eval/blob/9510044bf22e6fec46f1a49616b8f840d0caa415/.github/workflows/release_main.yml) manually off of the `dev` branch, but it's not clear to me that that would be able to release `main` (which has it's own version of that workflow file) without error.

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
