### PR TITLE
About & style revision

### PR DESCRIPTION
**Pull request by tildechris**
Update header styling, add github link and refine about text.

image

### CODE REVIEW

**Comment by kateharwood** [comment]
I'm seeing this 
Screen Shot 2021-03-12 at 12 55 29 PM

**Comment by tildechris** [comment]
That size issue is odd.  Can you try again with this style update?  Which browser are you using?

**Comment by kateharwood** [comment]
It's within rstudio, but it looks fine on my browser! Mind if I change the columns to 9 and 1 rather than 8 and 2, so the github element is aligned on the right side of the page like this?
Screen Shot 2021-03-15 at 12 05 14 PM

**Comment by tildechris** [comment]
Ah, that makes sense.  I wonder which rendering engine that RStudio uses that demonstrates this behavior but it's not present in Firefox or Chrome.

The columns define the width but not the justification.  We could do something like this:

```css
display: flex;
justify-content: flex-end;
```

Which looks like this: 
image

**Comment by kateharwood** [comment]
Yeah either way, that LGTM!

**Comment by tildechris** [comment]
Updated to right align.  I also tested this in RStudio and it renders like I would expect.  Can you review?

**Comment by kateharwood** [comment]
LGTM, in rstudio too!

**Review by kateharwood — APPROVED** [review]

**Pull request merged**
